spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#    generate-ddl: true

  application:
    name: app
  output:
    ansi:
      enabled: always

  profiles:
    default: development

sentry:
  dsn: https://c6d83bea1aa07268ebf000f011c57d62@o4508874985177088.ingest.de.sentry.io/4508875035443280
  traces-sample-rate: 1.0

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem